PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX lib: <http://www.semanticweb.org/m13/ontologies/2024/4/library/>
SELECT ?book ?title ?author
WHERE {
  ?book lib:title ?title .
  ?book lib:author ?author .
  FILTER regex(?author, $var, "i")
}
LIMIT 25